---
- name: Install packages needed from apt
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
  with_items:
  - apache2
  - libapache2-mod-wsgi

- name: Install apache modules needed
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
  - wsgi
  - expires
  - headers

- name: Ensure apache is running
  service:
    name: apache2
    state: started

- copy:
    src: deny_raw_access.conf
    dest: /etc/apache2/sites-available/deny_raw_access.conf

- name: Enable apache the prev config
  file:
    src: ../sites-available/deny_raw_access.conf
    dest: /etc/apache2/sites-enabled/deny_raw_access.conf
    state: link

- name: Disable apache default site
  file:
      path: "/etc/apache2/sites-enabled/000-default.conf"
      state: absent
  notify:
  - restart apache
