---
- hosts: VPS
  remote_user: root
  vars:
    echaloasuerte_root: "/data/apache/serve/echaloasuerte"
    echaloasuerte_app: "{{ echaloasuerte_root }}/web-app"
    echaloasuerte_venv: "{{ echaloasuerte_root }}/venv"
  tasks:
  - name: ensure git is installed
    apt: pkg=git state=present
  - name: ensure PIP is installed
    apt: pkg=python-pip state=present
  - pip: name=virtualenv
  - name: ensure gettext is installed
    apt: pkg=gettext state=present
  - pip: name=django virtualenv={{ echaloasuerte_venv }}
  - pip: name=django-bootstrap-form virtualenv={{ echaloasuerte_venv }}
  - pip: name=django-crispy-forms virtualenv={{ echaloasuerte_venv }}
  - pip: name=pytz

  - git: repo=git://github.com/etcaterva/EchaloASuerte.git dest={{ echaloasuerte_app }} update=yes accept_hostkey=True force=yes

  - name: Add virtualenv info in echaloasuerte.wsgi
    template: src=echaloasuerte/echaloasuerte.wsgi dest={{ echaloasuerte_app }}/echaloasuerte.wsgi
    notify:
    - restart apache

  - shell: |
           {{ echaloasuerte_venv }}/bin/python {{ echaloasuerte_app }}/manage.py compilemessages

  - django_manage: >
      command=syncdb
      app_path={{ echaloasuerte_app }}
      virtualenv={{ echaloasuerte_venv }}

  - django_manage: >
      command=collectstatic	
      app_path={{ echaloasuerte_app }}
      virtualenv={{ echaloasuerte_venv }}

  - name: Create echaloasuerte application tree
    file: path={{ item }} state=directory owner=www-data recurse=yes
    with_items:
    - "{{ echaloasuerte_root }}/logs"
    - "{{ echaloasuerte_root }}/static"
    - "{{ echaloasuerte_app }}"
    - "{{ echaloasuerte_venv }}"


  - name: ensure apache is installed
    apt: pkg=apache2 state=present
  - name: ensure libapache2-mod-wsgi is installed
    apt: pkg=libapache2-mod-wsgi state=present
  - apache2_module: state=present name=wsgi

  - name: write the apache config file
    template: src=echaloasuerte/echaloasuerte.conf dest=/etc/apache2/sites-available/echaloasuerte.conf
    notify:
    - restart apache

  - name: enable apache site ecaheloasuerte
    file: src=../sites-available/echaloasuerte.conf dest=/etc/apache2/sites-enabled/echaloasuerte.conf state=link
    notify:
    - restart apache

  - name: ensure apache is running
    service: name=apache2 state=started

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
