---
- hosts: VPS
  remote_user: root
  vars:
    datadir: "/data"
    mongodb_datadir_prefix: "{{ datadir }}/mongodb"
    mongodb_admin_user: siteadmin
    mongodb_admin_password: PASSSWORRRDD
  tasks:


# This apt_key may not be right
  - apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  - apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  - name: Install jenkins
    apt: name={{ item }} state=installed force=yes
    with_items:
    - jenkins

  - pip: name=ansible

  - service: name=jenkins state=started

# Add the user 'jenkins' to the user shadow
  - user: name=jenkins shell=/bin/bash groups=shadow,sudo append=yes
    notify:
    - restart jenkins


  - shell: wget localhost:8080/jnlpJars/jenkins-cli.jar -O /var/lib/jenkins/jenkins-cli.jar creates=/var/lib/jenkins/jenkins-cli.jar
    sudo: yes
    sudo_user: jenkins

  - name: Create Jenkins updates folder.
    file:
      path: /var/lib/jenkins/updates
      owner: jenkins
      group: jenkins
      mode: 0755
      state: directory

  - name: Update Jenkins plugin data.
    shell: >
      curl -L https://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
      creates=/var/lib/jenkins/updates/default.json

  - name: Permissions for default.json updates info.
    file:
      path: /var/lib/jenkins/updates/default.json
      owner: jenkins
      group: jenkins
      mode: 0755


  - name: Install Jenkins plugins.
    shell: >
      java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ install-plugin git
      creates=/var/lib/jenkins/plugins/git.jpi
    register: result
    until: result.rc == 0
    retries: 10
    delay: 1
    notify: restart jenkins

  - copy: src=jenkins/config.xml dest=/var/lib/jenkins/config.xml owner=jenkins group=jenkins
    notify:
    - restart jenkins

  handlers:
    - name: restart jenkins
      service: name=jenkins state=restarted

