---
- hosts: VPS
  remote_user: root
  vars:
    datadir: "/data"
    mongodb_datadir_prefix: "{{ datadir }}/mongodb"
    mongodb_admin_user: siteadmin
    mongodb_admin_password: PASSSWORRRDD
  tasks:


# This apt_key may not be right
  - apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  - apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  - name: Install jenkins
    apt: name={{ item }} state=installed force=yes
    with_items:
    - jenkins

  - name: start jenkins
    service: name=mongod enabled=yes state=started

