---
- hosts: VPS
  remote_user: root
  vars:
    datadir: "/data"
    mongodb_datadir_prefix: "{{ datadir }}/mongodb"
    mongodb_admin_user: siteadmin
    mongodb_admin_password: PASSSWORRRDD
  tasks:


# This apt_key may not be right
  - apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  - apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  - name: Install jenkins
    apt: name={{ item }} state=installed force=yes
    with_items:
    - jenkins

  - copy: src=jenkins/config.xml dest=/var/lib/jenkins/config.xml owner=jenkins group=jenkins
    notify:
    - restart jenkins

# Add the user 'jenkins' to the user shadow
  - user: name=jenkins shell=/bin/bash groups=shadow append=yes
    notify:
    - restart jenkins


  - shell: wget localhost:8080/jnlpJars/jenkins-cli.jar -O /var/lib/jenkins/jenkins-cli.jar creates=/var/lib/jenkins/jenkins-cli.jar
    sudo: yes
    sudo_user: jenkins


  handlers:
    - name: restart jenkins
      service: name=jenkins state=restarted

